=== FRuiMar/EjerciciosLMSGI_Propios/DTD/listadoEmpleados/listadoEmpleados.dtd
<!ELEMENT empleados (empleado*, departamentos, empresaMatriz, clientes)>
<!ELEMENT empleado (apellido+, departamento*, (responsable | subordinado)?)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT responsable EMPTY>
<!ELEMENT subordinado EMPTY>
<!ATTLIST empleado nombre (Francisco | Pepe | Javier | Susana) "Francisco"
                    edad CDATA #IMPLIED
                    antiguedad CDATA #REQUIRED
                    ciudadEmpresa CDATA #FIXED "MÃ¡laga"
                    codTrabaj ID #REQUIRED
                    codDepar IDREF #IMPLIED>
<!ELEMENT departamentos (#PCDATA | captacion | ventas)*>
<!ATTLIST departamentos listado IDREFS #REQUIRED>
<!ELEMENT captacion (#PCDATA)>
<!ELEMENT ventas (#PCDATA)>
<!ATTLIST captacion codDepar ID #REQUIRED>
<!ATTLIST ventas codDepar ID #REQUIRED>
<!ELEMENT empresaMatriz (#PCDATA)>
<!ENTITY madrid "Sucursal Madrid">
<!ELEMENT clientes (empresa, director)*>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ENTITY % atributoNombre "nombre CDATA #REQUIRED">
<!ATTLIST empresa %atributoNombre;>
<!ATTLIST director %atributoNombre;>

=== FRuiMar/EjerciciosLMSGI_Propios/DTD/listadoEmpleados/listadoEmpleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados SYSTEM "listadoEmpleados.dtd">
<empleados>
    <empleado nombre="Francisco" edad="42" antiguedad="7 años" ciudadEmpresa="Málaga" codTrabaj="Fra" codDepar="capt">
        <apellido>Ruiz</apellido>
        <departamento>captacion</departamento>
        <responsable />
    </empleado>
    <empleado nombre="Pepe" edad="38" antiguedad="5 años" ciudadEmpresa="Málaga" codTrabaj="Pep" codDepar="capt">
        <apellido>García</apellido>
        <departamento>captacion</departamento>
        <subordinado />
    </empleado>
    <empleado nombre="Javier" edad="33" antiguedad="3 años" ciudadEmpresa="Málaga" codTrabaj="Jav" codDepar="vent">
        <apellido>Perez</apellido>
        <departamento>ventas</departamento>
        <responsable />
    </empleado>
    <empleado nombre="Susana" edad="35" antiguedad="4 años" ciudadEmpresa="Málaga" codTrabaj="Sus" codDepar="vent">
        <apellido>Ruiz</apellido>
        <departamento>ventas</departamento>
        <responsable />
    </empleado>
    <departamentos listado="capt vent"> Los importantes
        <captacion codDepar="capt"></captacion>
        <ventas codDepar="vent"></ventas>
    </departamentos>
    <empresaMatriz>BBVA &madrid;</empresaMatriz>
    <clientes>
        <empresa nombre="Mercadona"/>
        <director nombre="ElJefe"/>
    </clientes>
</empleados>
